.gitmodules

<body>
add subject
<notes>
close #14

docs: #14 add data submodule

---

.gitmessage

[feat]: #16 add gittemplate

---

.github/ISSUE_TEMPLATE/command_issue.md

いい感じにcommandの説明を書けるtemplateを作りやした

feat/Create command_issue.md

---

inc/CommandHandler.hpp
inc/Replies.hpp
inc/Server.hpp
src/CommandHandler.cpp
src/Replies.cpp
src/Server.cpp

[feat]: #39 create command nick

---

inc/CommandHandler.hpp
inc/Server.hpp
src/CommandHandler_handleCommand.cpp
src/Server_run.cpp

このコミットでは、コマンド処理メカニズムを改修し、コマンド実行時に直接メッセージを送信する機能を統合しました。主な目的は、レスポンスの生成とクライアントへの送信方法を効率化し、コードベースの効率性と保守性を向上させることです。
変更点には以下が含まれます：
- `CommandHandler`の`handleCommand`を修正し、ファイルディスクリプタを引数として受け取るようにし、直接レスポンス送信を可能にしました。
- 個々のコマンドが直接レスポンスを送信できるように、`executeCommand`もファイルディスクリプタを受け取るように調整しました。
- 直接メッセージ送信をサポートするために`Server`クラスのメソッドを更新し、ファイルディスクリプタとメッセージを引数として取る新しい`sendReply`メソッドを含みます。
- コマンドレスポンス処理を簡素化するために、`Server_run.cpp`を新しい直接送信メカニズムを利用するようにリファクタリングしました。
これらの修正は、コマンドレスポンスフローを簡素化し、冗長性を減らし、サーバーの挙動をより予測可能でデバッグしやすくすることを目的としています。
[notes]
- この変更は、異なるコマンドシナリオに対する互換性と安定性を保証するために、徹底的なテストが必要です。
close #114

[feat]: #114 コマンド実行時のメッセージ送信を実装

---

inc/CommandHandler.hpp
inc/Replies.hpp
inc/Server.hpp
src/CommandHandler.cpp
src/CommandHandler_handleCommand.cpp
src/Replies.cpp
src/Server.cpp
src/User.cpp

[feat]: #41 create command oper message

---

inc/Replies.hpp
src/Replies.cpp

[style]: #121 fix order of replys

---

src/Server.cpp

[fix]: #127 fix isnick function

---

inc/CommandHandler.hpp
inc/Replies.hpp
inc/Server.hpp
src/CommandHandler.cpp
src/CommandHandler_handleCommand.cpp
src/Replies.cpp
src/Server.cpp

[feat]: 61 create command version message

---

inc/CommandHandler.hpp
inc/Replies.hpp
inc/Server.hpp
src/CommandHandler.cpp
src/CommandHandler_handleCommand.cpp
src/Replies.cpp
src/Server.cpp
src/Server_init.cpp

[feat]: 68 create command info command

---

inc/CommandHandler.hpp
inc/Replies.hpp
src/CommandHandler.cpp
src/CommandHandler_handleCommand.cpp
src/Replies.cpp

[feat]: 66 create command trace message

---

inc/CommandHandler.hpp
inc/Replies.hpp
inc/Server.hpp
src/CommandHandler.cpp
src/CommandHandler_handleCommand.cpp
src/Replies.cpp

[feat]: 67 create command admin command

---

src/CommandHandler_handleCommand.cpp

[feat]: #142 make links executable

---

inc/CommandHandler.hpp
inc/Server.hpp
src/CommandHandler.cpp

[feat]: #134 rejection-of-reserved-nick-name

---

src/CommandHandler_Join.cpp

[fix]: #181 channel mode k error

---

inc/Channel.hpp
inc/CommandHandler.hpp
inc/Server.hpp
src/Channel.cpp
src/CommandHandler_Error.cpp
src/CommandHandler_Kill.cpp
src/CommandHandler_Nick.cpp
src/CommandHandler_Notice.cpp
src/CommandHandler_Ping.cpp
src/CommandHandler_Pong.cpp
src/CommandHandler_Privmsg.cpp
src/CommandHandler_Quit.cpp
src/Server.cpp
src/Server_run.cpp

プルリクエストレビューで指摘された問題に対応し、CommandHandlerクラスとその関連メソッドをリファクタリングしました。具体的には、以下の変更を行いました。
- 各メソッドの定数性を強化し、変更不可のコンテキストで使用できるようにしました。
- 不正確なメソッド名を適切なものに変更し、コードの可読性を向上させました。
- 使用されていない変数とメソッドを削除し、コードの簡潔性を高めました。
これらの変更により、コードの保守性と可読性が向上し、将来的な拡張や変更が容易になります。
[notes]
close #182

[WIP][fix]: #182 プルリクエストレビューに基づくコードの改善

---

Makefile
inc/CommandHandler.hpp
inc/Server.hpp
inc/User.hpp
src/Channel.cpp
src/CommandHandler_Kill.cpp
src/CommandHandler_Ping.cpp
src/CommandHandler_Pong.cpp
src/CommandHandler_Whowas.cpp
src/CommandHandler_handleCommand.cpp
src/Server.cpp
src/Server_run.cpp
src/User.cpp

- オペレーター向けのKILLコマンドを処理するためのCommandHandler_Killを追加しました。
- ping/pong機能のためのCommandHandler_PingとCommandHandler_Pongを実装しました。
- pingとpongメッセージを管理するためのServerのメソッドを追加しました。
- pingのタイムアウトや非応答ユーザーの処理のためのエラーハンドリングを実装しました。

[feat]: #78 create command ping message

---

Makefile
irssi_conf/four.conf
irssi_conf/one.conf
irssi_conf/template.conf
irssi_conf/three.conf
irssi_conf/two.conf

MakefileにIrssiの設定ファイルを操作するための新しいターゲットを追加しました。これには、複数の設定ファイル(one.conf, two.conf, three.conf, four.conf)の作成と、これらを使用してIrssiを起動するためのコマンド(connect, connect_one, connect_two, connect_three, connect_four)が含まれます。これにより、異なる設定で簡単にIrssiをテストすることが可能になります。
[notes]
close #190

[feat]: #190 Irssi設定ファイルの追加

---

src/Server.cpp

[fix]: #198 deluser segv

---

src/CommandHandler_Join.cpp

[fix]: #200 JOIN のステータスのバグをなおしました

---

inc/Server.hpp
src/CommandHandler_Invite.cpp
src/CommandHandler_Topic.cpp
src/Server_run.cpp

[fix]: #202 fix Invite command
